### ISSUE TITLE
Hibernate mapping of REST-API

### ISSUE THREAD

**Issue by andvianello** [52North/sensorweb-client-core#26]
The mapping configuration to set the category parameter to offering property probably doesn't work.

I followed suggestions in the sensorweb forum: http://sensorweb.forum.52north.org/JS-Client-categories-and-FOI-tc4028118.html#a4028939

You can have a look at our implementation for [MONALISA Data Service](http://monalisasos.eurac.edu/MONALISA_data_service/#/map) (4.3.12 SOS version and Helgoland client) where the mapping works well if you use the "List selection" and you enter using the "Station-tab" but if you use the other tabs it doesn't work.
We are using the 4.3.12 SOS version and Helgoland client.

**Comment by janschulte** [comment]
I fixed this issue within the commit https://github.com/52North/sensorweb-client-core/commit/a4184301fa9f745bba4c3e21970d6b2dd5f98988. If you build a new helgoland version of the dev branch you should see all results, when using the list selection.
